name: niteon
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bot_toast: ^4.1.3
  # flutter_spinkit: ^5.1.0
  google_fonts: ^5.1.0
  # url_launcher: ^6.1.12
  # flutter_riverpod: ^2.3.3
  hive: ^2.2.3
  flutter_svg: ^2.0.4
  connectivity_plus: ^4.0.2
  # circle_progress_bar: ^0.1.2
  # flutter_inappwebview: ^5.7.2+3 
  webview_flutter: ^4.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - assets/images/
