name: niteon
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bot_toast: ^4.1.3
  get: ^4.6.5
  flutter_launcher_icons: ^0.13.0
  google_fonts: ^5.1.0
  hive: ^2.2.3
  flutter_svg: ^2.0.4
  connectivity_plus: ^4.0.2
  loading_animation_widget: ^1.2.1
  webview_flutter: ^4.7.0
  iconly:
  iconsax:
  loading_indicator: ^3.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_launcher_icons: "^0.13.0"
flutter_lints: ^2.0.0


flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icon.png"

flutter:

  uses-material-design: true

  assets:
   - assets/images/
